export interface WordEntry {
  word: string;
  hint: string;
}

const WORD_LISTS: Record<string, WordEntry[]> = {
  'Everyday Objects': [
    { word: 'Umbrella', hint: 'Rain' },
    { word: 'Toothbrush', hint: 'Morning' },
    { word: 'Mirror', hint: 'Reflection' },
    { word: 'Scissors', hint: 'Cutting' },
    { word: 'Candle', hint: 'Flame' },
    { word: 'Pillow', hint: 'Soft' },
    { word: 'Wallet', hint: 'Pocket' },
    { word: 'Sunglasses', hint: 'Summer' },
    { word: 'Backpack', hint: 'Travel' },
    { word: 'Watch', hint: 'Wrist' },
    { word: 'Headphones', hint: 'Music' },
    { word: 'Lighter', hint: 'Fire' },
    { word: 'Stapler', hint: 'Office' },
    { word: 'Broom', hint: 'Sweeping' },
    { word: 'Doorbell', hint: 'Visitor' },
    { word: 'Remote Control', hint: 'Couch' },
    { word: 'Keychain', hint: 'Jingle' },
    { word: 'Notebook', hint: 'Writing' },
    { word: 'Charger', hint: 'Battery' },
    { word: 'Mug', hint: 'Coffee' },
    { word: 'Blanket', hint: 'Warm' },
    { word: 'Flashlight', hint: 'Dark' },
    { word: 'Zipper', hint: 'Jacket' },
    { word: 'Pencil', hint: 'Drawing' },
    { word: 'Eraser', hint: 'Mistake' },
  ],
  'Famous People': [
    { word: 'Albert Einstein', hint: 'Physics' },
    { word: 'Elon Musk', hint: 'Rockets' },
    { word: 'Taylor Swift', hint: 'Pop music' },
    { word: 'Leonardo da Vinci', hint: 'Painting' },
    { word: 'Beyonce', hint: 'Destiny' },
    { word: 'Steve Jobs', hint: 'Apple' },
    { word: 'Cristiano Ronaldo', hint: 'Football' },
    { word: 'Oprah Winfrey', hint: 'Talk show' },
    { word: 'Michael Jordan', hint: 'Basketball' },
    { word: 'Shakespeare', hint: 'Theatre' },
    { word: 'Cleopatra', hint: 'Egypt' },
    { word: 'The Rock', hint: 'Wrestling' },
    { word: 'Adele', hint: 'Hello' },
    { word: 'Barack Obama', hint: 'President' },
    { word: 'Lionel Messi', hint: 'Argentina' },
    { word: 'Marie Curie', hint: 'Radiation' },
    { word: 'Tom Hanks', hint: 'Forrest' },
    { word: 'Rihanna', hint: 'Umbrella' },
    { word: 'Nelson Mandela', hint: 'Freedom' },
    { word: 'Drake', hint: 'Toronto' },
  ],
  'Foods & Drinks': [
    { word: 'Pizza', hint: 'Cheese' },
    { word: 'Sushi', hint: 'Raw' },
    { word: 'Tacos', hint: 'Shell' },
    { word: 'Ice Cream', hint: 'Cold' },
    { word: 'Espresso', hint: 'Beans' },
    { word: 'Avocado', hint: 'Green' },
    { word: 'Croissant', hint: 'French' },
    { word: 'Bubble Tea', hint: 'Pearls' },
    { word: 'Pancakes', hint: 'Syrup' },
    { word: 'Ramen', hint: 'Noodles' },
    { word: 'Chocolate', hint: 'Sweet' },
    { word: 'Burrito', hint: 'Wrapped' },
    { word: 'Cheesecake', hint: 'Dessert' },
    { word: 'Smoothie', hint: 'Blended' },
    { word: 'Popcorn', hint: 'Cinema' },
    { word: 'Mango', hint: 'Tropical' },
    { word: 'Waffles', hint: 'Grid' },
    { word: 'Nachos', hint: 'Dipping' },
    { word: 'Milkshake', hint: 'Straw' },
    { word: 'Pasta', hint: 'Italian' },
    { word: 'Steak', hint: 'Grilled' },
    { word: 'Donut', hint: 'Ring' },
    { word: 'Lobster', hint: 'Claws' },
    { word: 'Pretzel', hint: 'Twisted' },
    { word: 'Tiramisu', hint: 'Layers' },
  ],
  'Animals': [
    { word: 'Penguin', hint: 'Ice' },
    { word: 'Chameleon', hint: 'Colour' },
    { word: 'Dolphin', hint: 'Ocean' },
    { word: 'Red Panda', hint: 'Bamboo' },
    { word: 'Octopus', hint: 'Tentacles' },
    { word: 'Flamingo', hint: 'Pink' },
    { word: 'Koala', hint: 'Australia' },
    { word: 'Jellyfish', hint: 'Sting' },
    { word: 'Peacock', hint: 'Feathers' },
    { word: 'Hedgehog', hint: 'Spikes' },
    { word: 'Platypus', hint: 'Weird' },
    { word: 'Panda', hint: 'Black and white' },
    { word: 'Owl', hint: 'Night' },
    { word: 'Shark', hint: 'Teeth' },
    { word: 'Elephant', hint: 'Trunk' },
    { word: 'Sloth', hint: 'Slow' },
    { word: 'Cheetah', hint: 'Fast' },
    { word: 'Parrot', hint: 'Talking' },
    { word: 'Wolf', hint: 'Howl' },
    { word: 'Seahorse', hint: 'Tiny' },
  ],
  'Places': [
    { word: 'Eiffel Tower', hint: 'Iron' },
    { word: 'Grand Canyon', hint: 'Deep' },
    { word: 'Tokyo', hint: 'Neon' },
    { word: 'Amazon Rainforest', hint: 'Jungle' },
    { word: 'Great Wall of China', hint: 'Long' },
    { word: 'Venice', hint: 'Canals' },
    { word: 'Sahara Desert', hint: 'Sand' },
    { word: 'Hollywood', hint: 'Stars' },
    { word: 'Machu Picchu', hint: 'Ruins' },
    { word: 'Sydney Opera House', hint: 'Sails' },
    { word: 'Bermuda Triangle', hint: 'Missing' },
    { word: 'Times Square', hint: 'Billboards' },
    { word: 'Niagara Falls', hint: 'Water' },
    { word: 'Taj Mahal', hint: 'Marble' },
    { word: 'Antarctica', hint: 'Frozen' },
    { word: 'Las Vegas', hint: 'Gambling' },
    { word: 'Mount Everest', hint: 'Summit' },
    { word: 'Stonehenge', hint: 'Rocks' },
    { word: 'Vatican City', hint: 'Pope' },
    { word: 'Dubai', hint: 'Skyscrapers' },
  ],
  'Movies & TV Shows': [
    { word: 'Titanic', hint: 'Sinking' },
    { word: 'Breaking Bad', hint: 'Chemistry' },
    { word: 'The Lion King', hint: 'Simba' },
    { word: 'Stranger Things', hint: 'Upside down' },
    { word: 'Harry Potter', hint: 'Wand' },
    { word: 'Game of Thrones', hint: 'Dragons' },
    { word: 'Inception', hint: 'Dreams' },
    { word: 'Friends', hint: 'Couch' },
    { word: 'Star Wars', hint: 'Lightsaber' },
    { word: 'The Office', hint: 'Paper' },
    { word: 'Avatar', hint: 'Blue' },
    { word: 'Squid Game', hint: 'Survival' },
    { word: 'Jurassic Park', hint: 'Dinosaurs' },
    { word: 'The Simpsons', hint: 'Yellow' },
    { word: 'Batman', hint: 'Gotham' },
    { word: 'Frozen', hint: 'Snow' },
    { word: 'Spider-Man', hint: 'Web' },
    { word: 'Wednesday', hint: 'Addams' },
    { word: 'Shrek', hint: 'Swamp' },
    { word: 'The Matrix', hint: 'Red pill' },
  ],
};

export function pickRandomWord(categories: string[]): { word: string; hint: string; category: string } {
  const validCategories = categories.filter((cat) => WORD_LISTS[cat]);
  if (validCategories.length === 0) {
    return { word: 'Umbrella', hint: 'Rain', category: 'Everyday Objects' };
  }
  const category = validCategories[Math.floor(Math.random() * validCategories.length)];
  const words = WORD_LISTS[category];
  const entry = words[Math.floor(Math.random() * words.length)];
  return { word: entry.word, hint: entry.hint, category };
}
